<a href="https://colab.research.google.com/github/debstS/London-cycle-rental-analysis/blob/main/Cycle_rental_final_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# to mount Google drive files for accessing from within Google Colab

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import pandas as pd
import glob

In [ ]:
#copy and paste the path where the dataset is stored in your computer

os.chdir("/content/drive/MyDrive/TFL Cycle rental analysis - datasets")

In [ ]:
# Step 1: List all CSV files in the directory

csv_files = glob.glob("*.csv")  # Assumes all CSV files are in the same directory

#csv_files

# Step 2: Read each CSV file and store them in a list
df_list = []
for file in csv_files:
  #print(file)
    df = pd.read_csv(file,low_memory = False)
    df.rename(columns = {'Rental Id':'Number', 'Duration':'Total duration', 'Bike Id':'Bike number', 'End Date':'End date', 'EndStation Id':'End station number', 'EndStation Name':'End station', 'Start Date':'Start date', 'StartStation Id':'Start station number','StartStation Name':'Start station'}, inplace=True)
    #df = df[['Number', 'Start date','Start station number','Start station','End date','End station number','End station','Bike number','Total duration']]
    #df = df.reindex(columns=['mean',0,1,2,3,4])
    df_list.append(df)

In [ ]:
total_records_in_142csv_files = 0
for i, dfi in enumerate(df_list):
  #print(dfi.shape[0])
  total_records_in_142csv_files = total_records_in_142csv_files + dfi.shape[0]
total_records_in_142csv_files #30786752

30786752

In [ ]:
# #import polars as pl

df1 = pd.DataFrame({"A":[1,2,3], "B":[87,88,30]})
df2 = pd.DataFrame({"B":[4,5,6], "A":[1,2,3], "C":['a','c','c']})

df = pd.concat([df1, df2])
df

   A   B    C
0  1  87  NaN
1  2  88  NaN
2  3  30  NaN
0  1   4    a
1  2   5    c
2  3   6    c

In [ ]:
final_df = pd.DataFrame()
for i_list, dfi_list in enumerate(df_list):
  final_df = pd.concat([final_df, dfi_list], ignore_index=True)

final_df.shape

(30786752, 11)

In [ ]:
#final_df.head()
final_df[final_df['Number'] == 127293433]

,Number,Total duration,Bike number,End date,End station number,End station,Start date,Start station number,Start station,Bike model,Total duration (ms)
21722499,127293433,15m 45s,57158,2022-12-05 00:14,1182,"Notting Hill Gate Station, Notting Hill",2022-12-04 23:58,1152,"Marylebone Lane, Marylebone",CLASSIC,945616.0

In [ ]:
df_list[5].head(4)

,Number,Total duration,Bike number,End date,End station number,End station,Start date,Start station number,Start station
0,105305967,7260,18247,07/02/2021 21:32,785,"Aquatic Centre, Queen Elizabeth Olympic Park",07/02/2021 19:31,785,"Aquatic Centre, Queen Elizabeth Olympic Park"
1,105246421,4140,16694,03/02/2021 20:28,785,"Aquatic Centre, Queen Elizabeth Olympic Park",03/02/2021 19:19,785,"Aquatic Centre, Queen Elizabeth Olympic Park"
2,105320173,720,17329,09/02/2021 19:39,57,"Guilford Street , Bloomsbury",09/02/2021 19:27,804,"Good's Way, King's Cross"
3,105255530,300,9078,04/02/2021 15:49,386,"Moor Street, Soho",04/02/2021 15:44,88,"Bayley Street , Bloomsbury"

In [ ]:
df_list[140].head(4)

,Number,Start date,Start station number,Start station,End date,End station number,End station,Bike number,Bike model,Total duration,Total duration (ms)
0,136236504,2023-12-14 23:59,1052,"Soho Square , Soho",2023-12-15 00:08,1011,"Argyle Street, Kings Cross",41844,CLASSIC,9m 2s,542155
1,136236505,2023-12-14 23:59,1071,"Tower Gardens , Tower",2023-12-15 00:05,200021,"Hermitage Court, Wapping",41687,CLASSIC,5m 29s,329770
2,136236506,2023-12-14 23:59,200230,"Maplin Street, Mile End",2023-12-15 00:07,200030,"Driffield Road, Old Ford",51906,CLASSIC,7m 45s,465562
3,136236507,2023-12-14 23:59,1163,"Wardour Street, Soho",2023-12-15 00:17,200151,"Hoxton Station, Hoxton",58771,CLASSIC,17m 36s,1056636

In [ ]:
pd_list = pd.DataFrame({'col':df_list})
pd_list.head(5)

                                                 col
0         Rental Id  Duration  Bike Id          E...
1         Rental Id  Duration  Bike Id          E...
2         Rental Id  Duration  Bike Id          E...
3         Rental Id  Duration  Bike Id          E...
4         Rental Id  Duration  Bike Id          E...

In [ ]:
import pandas as pd

# Assuming df1 and df2 are your DataFrames

# Concatenate the DataFrames along the rows
#concatenated_df = pd.concat([df1, df2], ignore_index=True)

#If you want to keep all columns from both DataFrames:
#concatenated_df = pd.concat([df1, df2], ignore_index=True, sort=False)

#If you want to keep only unique columns from both DataFrames:
concatenated_df = pd.concat([df1, df2], ignore_index=True, sort=False).drop_duplicates()

# ignore_index=True ensures that the index is reset to maintain a continuous index in the resulting DataFrame

# Example:
# df1:
#    A  B  C
# 0  1  2  3
# 1  4  5  6

# df2:
#    A  C  D
# 0  7  8  9
# 1  10 11 12

# concatenated_df:
#     A   B   C     D
# 0   1   2   3   NaN
# 1   4   5   6   NaN
# 2   7  NaN  8   9
# 3  10  NaN  11  12

In [ ]:
dfs[141].head(1)

,Number,Start date,Start station number,Start station,End date,End station number,End station,Bike number,Bike model,Total duration,Total duration (ms)
0,136450327,2023-12-31 23:59,3433,"Sadlers Sports Centre, Finsbury",2024-01-01 00:19,3433,"Sadlers Sports Centre, Finsbury",17711,CLASSIC,20m 6s,1206838

In [ ]:
dfs[141].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209428 entries, 0 to 209427
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Number                209428 non-null  int64
 1   Start date            209428 non-null  object
 2   Start station number  209428 non-null  int64
 3   Start station         209428 non-null  object
 4   End date              209428 non-null  object
 5   End station number    209428 non-null  int64
 6   End station           209428 non-null  object
 7   Bike number           209428 non-null  int64
 8   Bike model            209428 non-null  object
 9   Total duration        209428 non-null  object
 10  Total duration (ms)   209428 non-null  int64
dtypes: int64(5), object(6)
memory usage: 17.6+ MB

In [ ]:
dfs[21].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296473 entries, 0 to 296472
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Rental Id          296473 non-null  int64
 1   Duration           296473 non-null  int64
 2   Bike Id            296473 non-null  int64
 3   End Date           296473 non-null  object
 4   EndStation Id      296473 non-null  int64
 5   EndStation Name    296473 non-null  object
 6   Start Date         296473 non-null  object
 7   StartStation Id    296473 non-null  int64
 8   StartStation Name  296473 non-null  object
dtypes: int64(5), object(4)
memory usage: 20.4+ MB

In [ ]:
dfs[141].head(5)

,Number,Start date,Start station number,Start station,End date,End station number,End station,Bike number,Bike model,Total duration,Total duration (ms)
0,136450327,2023-12-31 23:59,3433,"Sadlers Sports Centre, Finsbury",2024-01-01 00:19,3433,"Sadlers Sports Centre, Finsbury",17711,CLASSIC,20m 6s,1206838
1,136450328,2023-12-31 23:59,200094,"St. Bride Street, Holborn",2024-01-01 00:50,1135,"Claverton Street, Pimlico",30722,CLASSIC,51m 11s,3071423
2,136450329,2023-12-31 23:59,1196,"Vincent Square, Westminster",2024-01-01 00:16,1196,"Vincent Square, Westminster",52107,CLASSIC,17m 3s,1023305
3,136450330,2023-12-31 23:59,1220,"Imperial College, Knightsbridge",2024-01-01 00:12,3464,"Green Street, Mayfair",58456,CLASSIC,12m 51s,771575
4,136450331,2023-12-31 23:59,964,"Bath Street, St. Luke's",2024-01-01 00:32,3437,"Curzon Street, Mayfair",50838,CLASSIC,32m 25s,1945176

In [ ]:
dfs[21].head(4)

,Rental Id,Duration,Bike Id,End Date,EndStation Id,EndStation Name,Start Date,StartStation Id,StartStation Name
0,108236168,1080,461,28/05/2021 09:17,452,"St. Katharine's Way, Tower",28/05/2021 08:59,134,"Wapping High Street, Wapping"
1,108248572,840,19135,28/05/2021 15:32,841,"Tower Wharf, Bermondsey",28/05/2021 15:18,134,"Wapping High Street, Wapping"
2,108240926,1140,20426,28/05/2021 12:11,624,"Courland Grove, Wandsworth Road",28/05/2021 11:52,624,"Courland Grove, Wandsworth Road"
3,108165670,420,18717,26/05/2021 09:03,772,"Binfield Road, Stockwell",26/05/2021 08:56,624,"Courland Grove, Wandsworth Road"

In [ ]:
len(dfs)

142

In [ ]:
# Step 3: Merge DataFrames
merged_df = pd.concat(dfs, ignore_index=True)

In [ ]:
merged_df.shape

(30786752, 20)

In [ ]:
merged_df.head()

,Rental Id,Duration,Bike Id,End Date,EndStation Id,EndStation Name,Start Date,StartStation Id,StartStation Name,Number,Start date,Start station number,Start station,End date,End station number,End station,Bike number,Bike model,Total duration,Total duration (ms)
0,104820582.0,1620.0,22.0,03/01/2021 15:14,11.0,"Brunswick Square, Bloomsbury",03/01/2021 14:47,542.0,"Salmon Lane, Limehouse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,104816169.0,1740.0,10755.0,03/01/2021 13:26,542.0,"Salmon Lane, Limehouse",03/01/2021 12:57,546.0,"New Fetter Lane, Holborn",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,104757113.0,1620.0,18908.0,30/12/2020 15:00,239.0,"Warren Street Station, Euston",30/12/2020 14:33,779.0,"Houndsditch, Aldgate",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,104749458.0,780.0,18499.0,30/12/2020 09:21,766.0,"Ram Street, Wandsworth",30/12/2020 09:08,653.0,"Simpson Street, Clapham Junction",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,104788389.0,5400.0,15668.0,01/01/2021 16:29,655.0,"Crabtree Lane, Fulham",01/01/2021 14:59,655.0,"Crabtree Lane, Fulham",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Step 4: Write the merged DataFrame to a new CSV file
merged_df.to_csv("merged_file.csv", index=False)

print("Merged file created successfully.")